spring.profiles.active=test

#API URL
server.servlet.context-path=/api

#SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#EXTRA CONFIGS
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jpa.properties.jakarta.persistence.sharedCache.mode=UNSPECIFIED
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

#SWAGGER SORT

springdoc.swagger-ui.tagsSorter=alpha

#UTF-8

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true